ui_print "****************************************"
ui_print "⚡ FastCharge Hybrid Qualcomm GeN2"
ui_print "   by aifu-ID x AI"
ui_print "****************************************"
ui_print " Powered by KernelSU Next"
ui_print " "
ui_print "🔧 Initializing FastCharge Hybrid Qualcomm GeN2..."
ui_print "🔍 Powered by aifu-ID x AI | 🛠 Engine: service.sh"
ui_print " "
ui_print "🔧 Module Type: Systemless (Magisk/KSU)"
ui_print "👾 ROOT: Magisk, KernelSU (Ksu-Next/sukiSU Ultra/RKSU), Apatch"
ui_print " "
ui_print "🧠 Logic Engine:"
ui_print "📡 Monitor battery temp in real-time"
ui_print "⚡ Trigger cooldown at 41°C → resume charge ≤ 38°C"
ui_print " "
ui_print "🔄 Checking environment..."
if ! command -v busybox >/dev/null; then
  abort "❌ BusyBox not found! Module membutuhkan BusyBox."
fi
ui_print "✅ BusyBox: ✔ Detected ($(busybox | head -n 1))"
ui_print "✅ Root   : ✔ Valid (KSU/Next)"
ui_print "✅ Shell  : ✔ Sh + Su"
ui_print " "
ui_print "🔌 Activating Charging Control Core..."
ui_print "🔗 Mounting script: /system/bin/charge_cool.sh"
ui_print " "
ui_print "✅ Status: Module installed successfully!"
ui_print "🔁 Reboot to apply changes."
ui_print " "
ui_print "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ui_print "✅ FastCharge Hybrid Qualcomm GeN2 Loaded."
